前端vue项目改造
lich0821/wcf-client-rust pull request #18
Opened 2024-07-16 14:15 UTC by supermoonie

前端vue项目改造
增加Sql执行页面

2024-07-17 09:51 UTC, lich0821 requested changes
感谢大佬！

2024-07-17 09:51 UTC, lich0821 commented on .gitignore
> -.*
这个不能干掉，隐藏文件还是得显式添加，不然容易提交很多不必要的文件。

2024-07-17 09:51 UTC, lich0821 commented on src-tauri/src/main.rs
> +// }
直接干掉吧，留着没用。

2024-07-19 05:36 UTC, supermoonie commented on .gitignore
> -.*
前端有一些.开头的文件，不能排除掉

2024-07-19 05:37 UTC, supermoonie commented on src-tauri/src/main.rs
> +// }
最新代码已经去掉

2024-07-19 05:47 UTC, lich0821 requested changes
大佬又摸鱼了！

2024-07-19 05:47 UTC, lich0821 commented on .gitignore
> -.*
目前应该就一个 `.npmrc`，可以显式跟踪一下：
```
!.gitignore
!.github/
!.npmrc
```

2024-07-19 05:48 UTC, supermoonie commented on .gitignore
> -.*
okk

2024-07-19 05:50 UTC, supermoonie commented on .gitignore
> -.*
提交了

2024-07-19 08:41 UTC, lich0821 approved these changes
完成✅

2024-07-19 08:43 UTC, merged

2024-07-19 08:43 UTC, lich0821 commented
#12